In [0]:
import pandas as pd
import numpy as np
from numpy import savetxt
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.preprocessing import normalize

In [0]:
genre_df = pd.read_csv('data.csv')


In [0]:
Label = ["blues","classical","country","disco","hiphop","jazz","metal","pop","reggae","rock"]
op_cases = 4

In [0]:
def label_indexing(x):
  for i in range(10):
    if(x==Label[i]):
      return i

In [0]:
genre_df['label'] = genre_df['label'].apply(label_indexing)

In [0]:
data = genre_df.to_numpy()
X = data[0:400,1:29]
X = normalize(X)
y = np.zeros((X.shape[0],op_cases))

for i in range(X.shape[0]):
  y[i:i+1,:] = np.identity(op_cases)[data[i,29],:]

one=np.ones((X.shape[0],1))
X= np.append(one,X,axis=1)

In [32]:
print(y)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]


In [0]:
# make train, val and test sets
# seperate out test set
x_1,x_test,y_1,y_test=train_test_split(X,y,test_size=0.2)
#split remining into train and val set
x_train,x_val,y_train,y_val=train_test_split(x_1,y_1,test_size=0.25)

In [0]:
Train = np.append(x_train,y_train,axis=1) 
Val = np.append(x_val,y_val,axis=1)
Test = np.append(x_test,y_test,axis=1)
Header = 'x0,tempo, beats, chroma_stft, rmse,spectral_centroid, spectral_bandwidth, rolloff,zero_crossing_rate, mfcc1, mfcc2, mfcc3, mfcc4, mfcc5, mfcc6, mfcc7, mfcc8, mfcc9, mfcc10, mfcc11, mfcc12, mfcc13, mfcc14, mfcc15, mfcc16, mfcc17, mfcc18, mfcc19, mfcc20, y0, y1,y2,y3' 

In [0]:

savetxt('TrainData4.csv',Train,delimiter=',',header=Header)
savetxt('ValData4.csv',Val,delimiter=',',header=Header)
savetxt('TestData4.csv',Test,delimiter=',',header=Header)